const levels=[0.1,1,2,3,5,7,10,15,20,25,30,40,50,60,70,80,90,100,125,150,175,200,250,300,400,500,600,800];
const colors=['#f2f2f2','#c7dcff','#8ebfff','#4aa3ff','#007cff','#004b99','#1b5e20','#00c853','#64dd17','#c6ff00','#ffd600','#ffab00','#ff6d00','#ff8f00','#ff5c8a','#ff1f5b','#ff0033','#d50000','#7b1fa2','#6a00ff','#c000ff','#d580ff','#f0ccff','#d9d9d9','#a6a6a6','#7a7a7a','#4d4d4d','#333333'];
const map=L.map('map').setView([11,78.5],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
let layer=null, data=null;
function color(v){if(v==null||!isFinite(v)||v<levels[0])return null;let i=0;while(i<levels.length-1&&v>=levels[i+1])i++;return colors[Math.min(i,colors.length-1)]}
function draw(){if(!data)return; if(layer)map.removeLayer(layer); const p=+document.querySelector('#period').value; const op=+document.querySelector('#opacity').value; const selected=[...document.querySelectorAll('.model:checked')].map(x=>x.value); const features=[]; (data.grid||[]).forEach(g=>{let vals=selected.map(m=>(g.models||{})[m]?.[p]).filter(Number.isFinite);if(!vals.length)return;let v=vals.reduce((a,b)=>a+b,0)/vals.length;let c=color(v);if(!c)return;let d=data.step||0.25;features.push({type:'Feature',geometry:{type:'Polygon',coordinates:[[[g.lon-d/2,g.lat-d/2],[g.lon+d/2,g.lat-d/2],[g.lon+d/2,g.lat+d/2],[g.lon-d/2,g.lat+d/2],[g.lon-d/2,g.lat-d/2]]]},properties:{v}})}); layer=L.geoJSON({type:'FeatureCollection',features},{style:f=>({fillColor:color(f.properties.v),fillOpacity:op,color:color(f.properties.v),weight:0})}).addTo(map);}
function legend(){document.querySelector('#legend').innerHTML='<b>Rainfall (mm / 6h)</b><br>'+levels.map((x,i)=>`<span class="lg" style="background:${colors[i]}"></span>${i<levels.length-1?x+'–'+levels[i+1]:'>='+x}`).join('<br>')}
fetch('data.json?'+Date.now()).then(r=>r.json()).then(x=>{data=x;document.querySelector('#time').textContent=x.updated||'Latest update';draw();legend()}).catch(e=>{document.querySelector('#time').textContent='Data unavailable';console.error(e)});
document.querySelectorAll('.model,#period,#opacity').forEach(x=>x.addEventListener('change',draw));
